"""World Cup 2026 teams and player data.

Players come from app/data/players.json, generated by scripts/fetch_players.py
(Wikipedia final squads). Falls back to a short legacy list if the file is missing.
"""
import json
import logging
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

PLAYERS_PATH = Path(__file__).parent / "data" / "players.json"

TEAMS_48 = sorted([
    "Mexique","Afrique du Sud","Corée du Sud","Tchéquie",
    "Canada","Bosnie-Herzégovine","Qatar","Suisse",
    "Brésil","Maroc","Haïti","Écosse",
    "États-Unis","Paraguay","Australie","Turquie",
    "Allemagne","Curaçao","Côte d'Ivoire","Équateur",
    "Pays-Bas","Japon","Suède","Tunisie",
    "Belgique","Égypte","Iran","Nouvelle-Zélande",
    "Espagne","Cap-Vert","Arabie Saoudite","Uruguay",
    "France","Sénégal","Irak","Norvège",
    "Argentine","Algérie","Autriche","Jordanie",
    "Portugal","RD Congo","Ouzbékistan","Colombie",
    "Angleterre","Croatie","Ghana","Panama",
])

# Legacy fallback used only if players.json is absent.
LEGACY_SCORERS = [
    "Kylian Mbappé", "Harry Kane", "Erling Haaland",
    "Vinícius Júnior", "Lautaro Martínez", "Viktor Gyökeres", "Lamine Yamal",
    "Marcus Thuram", "Ousmane Dembélé", "Cole Palmer", "Bukayo Saka",
    "Nico Williams", "Cristiano Ronaldo", "Rafael Leão", "Cody Gakpo",
    "Romelu Lukaku", "Loïs Openda", "Julián Álvarez", "Luis Díaz",
    "Mohamed Salah", "Darwin Núñez", "Santiago Giménez", "Sadio Mané",
    "Alexander Sørloth", "Kaoru Mitoma", "Andrej Kramarić",
]


@lru_cache(maxsize=1)
def get_players() -> tuple:
    """All World Cup players as dicts: name, team, position, club."""
    try:
        with open(PLAYERS_PATH, encoding="utf-8") as f:
            return tuple(json.load(f))
    except Exception:
        logger.warning("players.json introuvable ou invalide — fallback liste réduite.")
        return tuple(
            {"name": name, "team": "", "position": "", "club": ""}
            for name in LEGACY_SCORERS
        )


def scorer_choice(player: dict) -> str:
    """Canonical value stored for a top-scorer pick, unambiguous across teams."""
    if player.get("team"):
        return f"{player['name']} ({player['team']})"
    return player["name"]


POSITION_LABELS_FR = {
    "GK": "Gardien",
    "DF": "Défenseur",
    "MF": "Milieu",
    "FW": "Attaquant",
}


@lru_cache(maxsize=1)
def get_scorer_choices() -> tuple:
    """Canonical top-scorer values, sorted by player name."""
    return tuple(sorted(
        (scorer_choice(p) for p in get_players()),
        key=lambda s: s.casefold(),
    ))


_POSITION_ORDER = {"GK": 0, "DF": 1, "MF": 2, "FW": 3}


@lru_cache(maxsize=1)
def get_scorer_options() -> tuple:
    """Structured options for the top-scorer combobox.

    Sorted for browsing: nation, then position (GK→FW), then player name —
    the combobox renders one group header per team in that order.
    """
    players = sorted(
        get_players(),
        key=lambda p: (
            (p.get("team") or "").casefold(),
            _POSITION_ORDER.get(p.get("position", ""), 4),
            p["name"].casefold(),
        ),
    )
    return tuple(
        {
            "value": scorer_choice(p),
            "name": p["name"],
            "team": p.get("team") or "",
            "position": POSITION_LABELS_FR.get(p.get("position", ""), ""),
        }
        for p in players
    )


def is_valid_scorer(value: str) -> bool:
    return value in get_scorer_choices()


def normalize_scorer(value: str) -> str:
    """Map a stored scorer value to its canonical form when unambiguous.

    Older drafts stored the bare player name; canonical values are "Name (Team)".
    Returns the input unchanged when it is already canonical or can't be resolved.
    """
    value = (value or "").strip()
    if not value or is_valid_scorer(value):
        return value
    matches = [p for p in get_players() if p["name"] == value]
    if len(matches) == 1:
        return scorer_choice(matches[0])
    return value
